sudo: required
services:
  - docker
language: bash
env:
  - sonarr_version=2.0.0.5319
script:
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
  - docker build --build-arg sonarr_version=$sonarr_version -t dtroncy/rpi-sonarr .
# push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag dtroncy/rpi-sonarr dtroncy/rpi-sonarr:$sonarr_version
      travis_wait docker push dtroncy/rpi-sonarr:$sonarr_version
      docker push dtroncy/rpi-sonarr
    fi
