sudo: required
services:
- docker
language: bash
env:
  - sonarr_version=2.0.0.5085
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build --build-arg sonarr_version=$sonarr_version -t dtroncy/rpi-sonarr .